package com.example.yuanbaossehook;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.os.SystemClock;

import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.charset.StandardCharsets;

/**
 * Localhost bridge server living in the module's own process.
 *
 * Why a socket instead of only the ContentProvider
 * ------------------------------------------------
 * The gateway runs inside YuanBao's process. Android 11+ package visibility filtering applies to
 * Binder lookups performed by an app that does not declare this module in its &lt;queries&gt;
 * element, which is the case here, so ContentResolver.call() can never reach the module from
 * inside YuanBao. Loopback TCP is not subject to that filter, so the injected process talks to
 * this server instead (and keeps the provider as a fast path for shell/self callers).
 *
 * Authentication: a 32 hex char token. The token is generated by the *host* process and written
 * into the host's own external files directory (Android/data/&lt;yuanbao&gt;/files/yb_bridge.json),
 * which the module can read through its Shizuku grant. That directory is only readable by the
 * owning app, by uid 2000 (shell) and by root, so possession of the token means the caller is
 * either YuanBao, the shell, or root. The file is re-read on every auth mismatch and periodically,
 * so a restarted host process picks up a fresh token immediately.
 *
 * Wire format (both directions, one request per connection):
 *     [4 byte big-endian length][UTF-8 JSON payload]
 *     request : {"method":"shell","token":"...","extras":{...}}
 *     response: {"ok":true,"result":"<json string>"} or {"ok":false,"error":"..."}
 *
 * The server binds loopback only and never exposes anything outside this device.
 */
final class BridgeServer {

    static final int PORT_FIRST = 8799;
    static final int PORT_LAST = 8809;
    static final String HOST_FILES_DIR =
            "/storage/emulated/0/Android/data/" + BridgeOps.YUANBAO + "/files";
    static final String HANDSHAKE_PATH = HOST_FILES_DIR + "/yb_bridge.json";
    private static final String PREFS = "yb_bridge";
    private static final String KEY_TOKEN = "module_token";
    /** Last host token that authenticated successfully; persisted so restarts need no Shizuku. */
    private static final String KEY_HOST_TOKEN = "host_bridge_token";
    private static final int MAX_FRAME = 96 * 1024 * 1024;
    /**
     * How long a cached host token is trusted without re-reading the handshake file.
     *
     * The host keeps its token stable across process restarts (it is rotated once a day) and the
     * token is only ever handed to this module, so trusting it for a while is safe - and it keeps
     * reading the file (a Shizuku `cat`, the slowest step in the whole path) out of the hot path.
     * A mismatch still triggers a forced re-read, so a rotated token is picked up immediately.
     */
    private static final long TOKEN_TRUST_MS = 30L * 60L * 1000L;

    private static final Object LOCK = new Object();
    private static ServerSocket server;
    private static Thread acceptor;
    private static volatile int port;
    private static volatile long startedAt;
    private static volatile long tokenAt;
    private static volatile String hostToken = "";
    private static volatile String lastError = "";
    private static volatile int served;
    private static volatile int rejected;
    private static volatile String lastPeer = "";
    private static volatile long lastServedAt;

    private BridgeServer() {}

    // ------------------------------------------------------------------ token handshake

    /** Token published by the host process in its own external files dir, read through Shizuku. */
    private static String readHostToken() {
        try {
            ShizukuShell.Result r = ShizukuShell.exec("cat " + ShizukuShell.q(HANDSHAKE_PATH) + " 2>/dev/null", 8000L, null);
            if (r == null || !r.ok || r.stdout == null) return "";
            String s = r.stdout.trim();
            int brace = s.indexOf('{');
            if (brace < 0) return "";
            JSONObject o = new JSONObject(s.substring(brace));
            return o.optString("token", "");
        } catch (Throwable t) {
            return "";
        }
    }

    private static synchronized String refreshToken(boolean force) {
        long now = SystemClock.elapsedRealtime();
        if (!force && !hostToken.isEmpty() && now - tokenAt < TOKEN_TRUST_MS) return hostToken;
        tokenAt = now;
        String t = readHostToken();
        if (!t.isEmpty()) {
            hostToken = t;
            persistHostToken(t);
        } else if (hostToken.isEmpty()) {
            lastError = "等待宿主进程写入握手令牌: " + HANDSHAKE_PATH;
        }
        return hostToken;
    }

    /**
     * Host token used by the daemon launcher/probe. Shares the very same handshake as the socket
     * bridge and only touches Shizuku when nothing has been cached yet, so a heartbeat probe stays
     * cheap.
     */
    static String currentHostToken() {
        String t = refreshToken(false);
        if (t.isEmpty()) t = refreshToken(true);
        return t;
    }

    /** Loads the token from the last successful handshake so a restart never blocks on Shizuku. */
    private static void preloadHostToken(Context ctx) {
        try {
            Context c = ctx != null ? ctx : appContext();
            if (c == null || !hostToken.isEmpty()) return;
            String t = c.getSharedPreferences(PREFS, Context.MODE_PRIVATE).getString(KEY_HOST_TOKEN, "");
            if (t != null && t.length() >= 16) {
                hostToken = t;
                tokenAt = SystemClock.elapsedRealtime();
                BridgeOps.log("host token preloaded from prefs");
            }
        } catch (Throwable ignored) {}
    }

    private static void persistHostToken(String token) {
        try {
            Context c = appContext();
            if (c == null || token == null || token.isEmpty()) return;
            SharedPreferences p = c.getSharedPreferences(PREFS, Context.MODE_PRIVATE);
            if (!token.equals(p.getString(KEY_HOST_TOKEN, ""))) {
                p.edit().putString(KEY_HOST_TOKEN, token).apply();
            }
        } catch (Throwable ignored) {}
    }

    /** True while tool calls are flowing, i.e. when keeping Shizuku's shell warm is worth it. */
    static boolean activeRecently() {
        long at = lastServedAt;
        return at > 0L && SystemClock.elapsedRealtime() - at < 120000L;
    }

    /** Token this module would use when the host file is unavailable (persisted for diagnostics). */
    static String localToken(Context ctx) {
        try {
            SharedPreferences p = ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE);
            String t = p.getString(KEY_TOKEN, "");
            if (t == null || t.isEmpty()) {
                StringBuilder sb = new StringBuilder();
                java.security.SecureRandom rnd = new java.security.SecureRandom();
                for (int i = 0; i < 32; i++) sb.append("0123456789abcdef".charAt(rnd.nextInt(16)));
                t = sb.toString();
                p.edit().putString(KEY_TOKEN, t).apply();
            }
            return t;
        } catch (Throwable t) {
            return "";
        }
    }

    // ------------------------------------------------------------------ lifecycle

    static boolean isRunning() { return server != null && !server.isClosed(); }

    static JSONObject status(Context ctx) {
        JSONObject o = new JSONObject();
        try {
            o.put("running", isRunning());
            o.put("port", port);
            o.put("pid", android.os.Process.myPid());
            o.put("uid", android.os.Process.myUid());
            o.put("served", served);
            o.put("rejected", rejected);
            o.put("tokenReady", !hostToken.isEmpty());
            o.put("tokenAgeMs", tokenAt == 0 ? -1L : (SystemClock.elapsedRealtime() - tokenAt));
            o.put("handshakePath", HANDSHAKE_PATH);
            o.put("startedAt", startedAt);
            o.put("lastPeer", lastPeer);
            o.put("lastError", lastError);
            o.put("shizukuGranted", ShizukuShell.status().optBoolean("permissionGranted", false));
            o.put("safMounted", SafStorage.mounted(ctx));
            // Standalone shell daemon state (cached probe: this runs on the main thread too).
            o.put("daemon", DaemonLauncher.status(ctx));
        } catch (Throwable t) {
            // status must never throw: it is the diagnostic surface itself
        }
        return o;
    }

    static void startAsync(final Context ctx) {
        Thread t = new Thread(new Runnable() {
            @Override public void run() {
                try { start(ctx); } catch (Throwable ignored) { }
            }
        }, "yb-bridge-start");
        t.setDaemon(true);
        t.start();
    }

    static synchronized JSONObject start(Context ctx) {
        if (isRunning()) return status(ctx);
        try {
            attach(ctx);
            preloadHostToken(ctx);
            ServerSocket ss = null;
            int bound = 0;
            for (int p = PORT_FIRST; p <= PORT_LAST; p++) {
                try {
                    ServerSocket cand = new ServerSocket();
                    cand.setReuseAddress(true);
                    cand.bind(new InetSocketAddress(InetAddress.getByName("127.0.0.1"), p), 16);
                    ss = cand;
                    bound = p;
                    break;
                } catch (Throwable taken) {
                    // port busy: try the next one in the range
                }
            }
            if (ss == null) throw new IOException("端口 " + PORT_FIRST + "-" + PORT_LAST + " 全部被占用");
            server = ss;
            port = bound;
            startedAt = System.currentTimeMillis();
            lastError = "";
            Thread t = new Thread(new Runnable() {
                @Override public void run() { acceptLoop(); }
            }, "yb-bridge-accept");
            t.setDaemon(true);
            acceptor = t;
            t.start();
            BridgeOps.log("bridge listening on 127.0.0.1:" + bound + " pid=" + android.os.Process.myPid());
            // The first Shizuku exec in a fresh module process pays Shizuku's user-service startup
            // cost (tens of seconds up to minutes on some ROMs). Paying it here, off the caller's
            // thread and before the host's first request arrives, is what keeps the first tool call
            // from looking like a hang.
            Thread tokenThread = new Thread(new Runnable() {
                @Override public void run() {
                    try {
                        ShizukuShell.warmUp();
                        String tok = refreshToken(true);
                        BridgeOps.log("handshake token ready len=" + tok.length());
                    } catch (Throwable e) {
                        BridgeOps.log("handshake warm-up failed: " + e);
                    }
                }
            }, "yb-bridge-token");
            tokenThread.setDaemon(true);
            tokenThread.start();
        } catch (Throwable t) {
            lastError = "启动失败: " + t;
            BridgeOps.log("bridge start failed: " + t);
        }
        return status(ctx);
    }

    static synchronized void stop() {
        try { if (server != null) server.close(); } catch (Throwable ignored) {}
        server = null;
        acceptor = null;
        port = 0;
        BridgeOps.log("bridge stopped");
    }

    private static volatile long lastTouchAt;

    /**
     * Opportunistic Shizuku warm-up, decoupled from the accept loop. At most one attempt every 2s and
     * always on its own thread, so a stuck Shizuku can never stop the bridge from answering.
     */
    private static void warmShizukuAsync() {
        long now = System.currentTimeMillis();
        if (now - lastTouchAt < 2000L) return;
        lastTouchAt = now;
        Thread t = new Thread(new Runnable() {
            @Override public void run() {
                try { ShizukuShell.touch(); } catch (Throwable ignored) {}
            }
        }, "yb-bridge-touch");
        t.setDaemon(true);
        t.start();
    }

    private static void acceptLoop() {
        while (true) {
            ServerSocket ss = server;
            if (ss == null || ss.isClosed()) return;
            Socket s = null;
            try {
                s = ss.accept();
                // A fresh connection usually means the host just (re)started and will send its first
                // tool call shortly, so warming Shizuku up now saves the cold start on that call.
                // It MUST NOT run on this thread: a slow or hanging Shizuku bind used to stop the
                // accept loop, leaving later connections unanswered in the backlog (the host then
                // saw "connected but no reply" instead of a clean fallback).
                warmShizukuAsync();
                final Socket cs = s;
                Thread h = new Thread(new Runnable() {
                    @Override public void run() { handle(cs); }
                }, "yb-bridge-conn");
                h.setDaemon(true);
                h.start();
            } catch (Throwable t) {
                if (ss.isClosed()) return;
                // A single failed accept must not kill the server; refresh the handshake token and retry.
                refreshToken(true);
                try { Thread.sleep(200L); } catch (InterruptedException ie) { Thread.currentThread().interrupt(); return; }
            } finally {
                if (s == null) refreshToken(false);
            }
        }
    }
    // ------------------------------------------------------------------ connection handling

    private static volatile Context appCtx;

    static void attach(Context c) {
        try { if (c != null) appCtx = c.getApplicationContext(); } catch (Throwable ignored) {}
    }

    private static Context appContext() {
        Context c = appCtx;
        if (c == null) c = ShizukuShell.context();
        return c;
    }

    private static void handle(Socket s) {
        String peer = "";
        try {
            peer = String.valueOf(s.getRemoteSocketAddress());
            s.setSoTimeout(30000);
            s.setTcpNoDelay(true);
            InputStream raw = new BufferedInputStream(s.getInputStream(), 65536);
            OutputStream out = new BufferedOutputStream(s.getOutputStream(), 65536);
            JSONObject req = readFrame(raw);
            String method = req.optString("method", "");
            String token = req.optString("token", "");
            Bundle extras = extrasOf(req.optJSONObject("extras"));

            String expected = refreshToken(false);
            if (expected.isEmpty()) expected = refreshToken(true);
            boolean authed = !expected.isEmpty() && expected.equals(token);
            if (!authed) {
                // The host may have restarted with a fresh token: re-read the handshake once
                // before rejecting, which removes any staleness window.
                expected = refreshToken(true);
                authed = !expected.isEmpty() && expected.equals(token);
            }
            if (!authed) {
                rejected++;
                lastPeer = peer;
                String reason = expected.isEmpty()
                        ? "bridge token 未就绪（宿主进程尚未写入握手文件）"
                        : "bridge token 不匹配";
                BridgeOps.log("reject: " + reason + " peer=" + peer + " method=" + method);
                writeFrame(out, new JSONObject().put("ok", false).put("error", reason));
                return;
            }
            lastPeer = peer;
            persistHostToken(token);
            long t0 = SystemClock.elapsedRealtime();
            JSONObject result = BridgeOps.dispatch(appContext(), method, extras, "socket");
            served++;
            lastServedAt = SystemClock.elapsedRealtime();
            lastError = "";
            BridgeOps.log("socket " + method + " peer=" + peer + " took="
                    + (SystemClock.elapsedRealtime() - t0) + "ms ok=" + result.optBoolean("ok", false));
            writeFrame(out, new JSONObject().put("ok", true).put("result", result.toString()));
        } catch (Throwable t) {
            lastError = "handle: " + t;
            BridgeOps.log("bridge connection failed peer=" + peer + ": " + t);
            try {
                writeFrame(s.getOutputStream(), new JSONObject().put("ok", false).put("error", "bridge error: " + t));
            } catch (Throwable ignored) {}
        } finally {
            try { s.close(); } catch (Throwable ignored) {}
        }
    }

    /** Reads one length-prefixed frame. */
    private static JSONObject readFrame(InputStream in) throws IOException {
        DataInputStream din = new DataInputStream(in);
        int len = din.readInt();
        if (len <= 0 || len > MAX_FRAME) throw new IOException("非法帧长度: " + len);
        byte[] buf = new byte[len];
        din.readFully(buf);
        try {
            return new JSONObject(new String(buf, StandardCharsets.UTF_8));
        } catch (Throwable t) {
            throw new IOException("请求 JSON 解析失败: " + t);
        }
    }

    /** Writes one length-prefixed frame. */
    private static void writeFrame(OutputStream out, JSONObject payload) throws IOException {
        byte[] b = payload.toString().getBytes(StandardCharsets.UTF_8);
        DataOutputStream dout = new DataOutputStream(out);
        dout.writeInt(b.length);
        dout.write(b);
        dout.flush();
    }

    /** JSON extras -> Bundle. Numbers become Integer/Long/Double; BridgeOps accessors accept any Number. */
    private static Bundle extrasOf(JSONObject o) {
        Bundle b = new Bundle();
        if (o == null) return b;
        try {
            java.util.Iterator<String> it = o.keys();
            while (it.hasNext()) {
                String k = it.next();
                Object v = o.opt(k);
                if (v == null || v == JSONObject.NULL) continue;
                if (v instanceof String) b.putString(k, (String) v);
                else if (v instanceof Boolean) b.putBoolean(k, (Boolean) v);
                else if (v instanceof Integer) b.putInt(k, (Integer) v);
                else if (v instanceof Long) b.putLong(k, (Long) v);
                else if (v instanceof Number) b.putDouble(k, ((Number) v).doubleValue());
                else b.putString(k, String.valueOf(v));
            }
        } catch (Throwable ignored) {}
        return b;
    }
}
